include:
- local: ".gitlab/ci/build_rs_core.yml"
- local: ".gitlab/ci/build_js_sdks.yml"
- local: ".gitlab/ci/build_server.yml"
- local: ".gitlab/ci/deploy_pages.yml"
stages:
- setup
- check
- build
- publish
- deploy
- test
default:
  tags:
  - dind
sast:
  stage: test
trivy_dependency_scan:
  stage: test
  image:
    name: aquasec/trivy:0.62.1
    entrypoint: [""]
  script:
    - trivy fs --scanners vuln --exit-code 1 --severity HIGH,CRITICAL .