// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/event_key.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PublicKey } from "./identity";
/**
 * EventKey's are the unique identitifiers of Events
 *
 * @generated from protobuf message polycentric.v2.EventKey
 */
export interface EventKey {
    /**
     * ID of the stream the event is connected with
     *
     * @generated from protobuf field: string stream_id = 1
     */
    streamId: string;
    /**
     * Public key that signed the event
     *
     * @generated from protobuf field: polycentric.v2.PublicKey signed_by = 2
     */
    signedBy?: PublicKey;
    /**
     * Sequence number of the event in the event stream (our logical clock)
     *
     * @generated from protobuf field: uint64 sequence = 3
     */
    sequence: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class EventKey$Type extends MessageType<EventKey> {
    constructor() {
        super("polycentric.v2.EventKey", [
            { no: 1, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "signed_by", kind: "message", T: () => PublicKey },
            { no: 3, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<EventKey>): EventKey {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.streamId = "";
        message.sequence = 0n;
        if (value !== undefined)
            reflectionMergePartial<EventKey>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventKey): EventKey {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_id */ 1:
                    message.streamId = reader.string();
                    break;
                case /* polycentric.v2.PublicKey signed_by */ 2:
                    message.signedBy = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.signedBy);
                    break;
                case /* uint64 sequence */ 3:
                    message.sequence = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventKey, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_id = 1; */
        if (message.streamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamId);
        /* polycentric.v2.PublicKey signed_by = 2; */
        if (message.signedBy)
            PublicKey.internalBinaryWrite(message.signedBy, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* uint64 sequence = 3; */
        if (message.sequence !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.sequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventKey
 */
export const EventKey = new EventKey$Type();
