// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IdentityService } from "./identity_service";
import type { InvitationStatus } from "./identity_service";
import type { GetInvitationStatusRequest } from "./identity_service";
import type { IdentityInvitation } from "./identity_service";
import type { SignedMessage } from "./server";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { EventBundle } from "./events";
import type { GetIdentityStateRequest } from "./identity_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export interface IIdentityServiceClient {
    /**
     * @generated from protobuf rpc: GetIdentityState
     */
    getIdentityState(input: GetIdentityStateRequest, options?: RpcOptions): UnaryCall<GetIdentityStateRequest, EventBundle>;
    /**
     * @generated from protobuf rpc: CreateInvitation
     */
    createInvitation(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IdentityInvitation>;
    /**
     * @generated from protobuf rpc: GetInvitationStatus
     */
    getInvitationStatus(input: GetInvitationStatusRequest, options?: RpcOptions): UnaryCall<GetInvitationStatusRequest, InvitationStatus>;
    /**
     * @generated from protobuf rpc: ClaimInvitation
     */
    claimInvitation(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, InvitationStatus>;
}
/**
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export class IdentityServiceClient implements IIdentityServiceClient, ServiceInfo {
    typeName = IdentityService.typeName;
    methods = IdentityService.methods;
    options = IdentityService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetIdentityState
     */
    getIdentityState(input: GetIdentityStateRequest, options?: RpcOptions): UnaryCall<GetIdentityStateRequest, EventBundle> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetIdentityStateRequest, EventBundle>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateInvitation
     */
    createInvitation(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IdentityInvitation> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, IdentityInvitation>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetInvitationStatus
     */
    getInvitationStatus(input: GetInvitationStatusRequest, options?: RpcOptions): UnaryCall<GetInvitationStatusRequest, InvitationStatus> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetInvitationStatusRequest, InvitationStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClaimInvitation
     */
    claimInvitation(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, InvitationStatus> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, InvitationStatus>("unary", this._transport, method, opt, input);
    }
}
