// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { SignedMessage } from "./server";
import { EventBundle } from "./events";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PublicKey } from "./keypair";
/**
 * Identity invitation for multi-device pairing
 *
 * @generated from protobuf message polycentric.v2.IdentityInvitation
 */
export interface IdentityInvitation {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
    /**
     * @generated from protobuf field: int64 created_at = 2
     */
    createdAt: bigint;
    /**
     * @generated from protobuf field: int32 ttl_seconds = 3
     */
    ttlSeconds: number;
}
/**
 * Body for claiming an invitation (what gets signed)
 *
 * @generated from protobuf message polycentric.v2.ClaimInvitationBody
 */
export interface ClaimInvitationBody {
    /**
     * @generated from protobuf field: string invitation_signature = 1
     */
    invitationSignature: string;
}
/**
 * @generated from protobuf message polycentric.v2.InvitationStatus
 */
export interface InvitationStatus {
    /**
     * @generated from protobuf field: polycentric.v2.IdentityInvitation invitation = 1
     */
    invitation?: IdentityInvitation;
    /**
     * @generated from protobuf field: repeated polycentric.v2.PublicKey claimers = 2
     */
    claimers: PublicKey[];
    /**
     * @generated from protobuf field: bool expired = 3
     */
    expired: boolean;
}
/**
 * @generated from protobuf message polycentric.v2.GetInvitationStatusRequest
 */
export interface GetInvitationStatusRequest {
    /**
     * @generated from protobuf field: string invitation_signature = 1
     */
    invitationSignature: string;
}
/**
 * @generated from protobuf message polycentric.v2.GetIdentityStateRequest
 */
export interface GetIdentityStateRequest {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class IdentityInvitation$Type extends MessageType<IdentityInvitation> {
    constructor() {
        super("polycentric.v2.IdentityInvitation", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "ttl_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<IdentityInvitation>): IdentityInvitation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        message.createdAt = 0n;
        message.ttlSeconds = 0;
        if (value !== undefined)
            reflectionMergePartial<IdentityInvitation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityInvitation): IdentityInvitation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                case /* int64 created_at */ 2:
                    message.createdAt = reader.int64().toBigInt();
                    break;
                case /* int32 ttl_seconds */ 3:
                    message.ttlSeconds = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityInvitation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        /* int64 created_at = 2; */
        if (message.createdAt !== 0n)
            writer.tag(2, WireType.Varint).int64(message.createdAt);
        /* int32 ttl_seconds = 3; */
        if (message.ttlSeconds !== 0)
            writer.tag(3, WireType.Varint).int32(message.ttlSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityInvitation
 */
export const IdentityInvitation = new IdentityInvitation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClaimInvitationBody$Type extends MessageType<ClaimInvitationBody> {
    constructor() {
        super("polycentric.v2.ClaimInvitationBody", [
            { no: 1, name: "invitation_signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ClaimInvitationBody>): ClaimInvitationBody {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.invitationSignature = "";
        if (value !== undefined)
            reflectionMergePartial<ClaimInvitationBody>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClaimInvitationBody): ClaimInvitationBody {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string invitation_signature */ 1:
                    message.invitationSignature = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClaimInvitationBody, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string invitation_signature = 1; */
        if (message.invitationSignature !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.invitationSignature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ClaimInvitationBody
 */
export const ClaimInvitationBody = new ClaimInvitationBody$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InvitationStatus$Type extends MessageType<InvitationStatus> {
    constructor() {
        super("polycentric.v2.InvitationStatus", [
            { no: 1, name: "invitation", kind: "message", T: () => IdentityInvitation },
            { no: 2, name: "claimers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PublicKey },
            { no: 3, name: "expired", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<InvitationStatus>): InvitationStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.claimers = [];
        message.expired = false;
        if (value !== undefined)
            reflectionMergePartial<InvitationStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InvitationStatus): InvitationStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.IdentityInvitation invitation */ 1:
                    message.invitation = IdentityInvitation.internalBinaryRead(reader, reader.uint32(), options, message.invitation);
                    break;
                case /* repeated polycentric.v2.PublicKey claimers */ 2:
                    message.claimers.push(PublicKey.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool expired */ 3:
                    message.expired = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InvitationStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.IdentityInvitation invitation = 1; */
        if (message.invitation)
            IdentityInvitation.internalBinaryWrite(message.invitation, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.PublicKey claimers = 2; */
        for (let i = 0; i < message.claimers.length; i++)
            PublicKey.internalBinaryWrite(message.claimers[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool expired = 3; */
        if (message.expired !== false)
            writer.tag(3, WireType.Varint).bool(message.expired);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.InvitationStatus
 */
export const InvitationStatus = new InvitationStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetInvitationStatusRequest$Type extends MessageType<GetInvitationStatusRequest> {
    constructor() {
        super("polycentric.v2.GetInvitationStatusRequest", [
            { no: 1, name: "invitation_signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetInvitationStatusRequest>): GetInvitationStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.invitationSignature = "";
        if (value !== undefined)
            reflectionMergePartial<GetInvitationStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetInvitationStatusRequest): GetInvitationStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string invitation_signature */ 1:
                    message.invitationSignature = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetInvitationStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string invitation_signature = 1; */
        if (message.invitationSignature !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.invitationSignature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetInvitationStatusRequest
 */
export const GetInvitationStatusRequest = new GetInvitationStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetIdentityStateRequest$Type extends MessageType<GetIdentityStateRequest> {
    constructor() {
        super("polycentric.v2.GetIdentityStateRequest", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetIdentityStateRequest>): GetIdentityStateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        if (value !== undefined)
            reflectionMergePartial<GetIdentityStateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetIdentityStateRequest): GetIdentityStateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetIdentityStateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetIdentityStateRequest
 */
export const GetIdentityStateRequest = new GetIdentityStateRequest$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.IdentityService
 */
export const IdentityService = new ServiceType("polycentric.v2.IdentityService", [
    { name: "GetIdentityState", options: {}, I: GetIdentityStateRequest, O: EventBundle },
    { name: "CreateInvitation", options: {}, I: SignedMessage, O: IdentityInvitation },
    { name: "GetInvitationStatus", options: {}, I: GetInvitationStatusRequest, O: InvitationStatus },
    { name: "ClaimInvitation", options: {}, I: SignedMessage, O: InvitationStatus }
]);
