// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IdentityService } from "./identity_service";
import type { IsBannedResponse } from "./identity_service";
import type { SetBanStatusResponse } from "./identity_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { IsModeratorResponse } from "./identity_service";
import type { SignedMessage } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Identity APIs.
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export interface IIdentityServiceClient {
    /**
     * Returns whether an identity is a moderator on this server. This
     * endpoint expects a signed IsModeratorBody message, signed by one of
     * the identity's authorized keys.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsModeratorResponse>;
    /**
     * Bans or unbans an identity on this server. This endpoint expects a
     * signed SetBanStatusBody message, signed by one of the moderator's
     * authorized keys.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, SetBanStatusResponse>;
    /**
     * Returns whether an identity is banned on this server. This endpoint
     * expects a signed IsBannedBody message, signed by one of the
     * moderator's authorized keys.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsBannedResponse>;
}
/**
 * *
 * Identity APIs.
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export class IdentityServiceClient implements IIdentityServiceClient, ServiceInfo {
    typeName = IdentityService.typeName;
    methods = IdentityService.methods;
    options = IdentityService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns whether an identity is a moderator on this server. This
     * endpoint expects a signed IsModeratorBody message, signed by one of
     * the identity's authorized keys.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsModeratorResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, IsModeratorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Bans or unbans an identity on this server. This endpoint expects a
     * signed SetBanStatusBody message, signed by one of the moderator's
     * authorized keys.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, SetBanStatusResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, SetBanStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Returns whether an identity is banned on this server. This endpoint
     * expects a signed IsBannedBody message, signed by one of the
     * moderator's authorized keys.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsBannedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, IsBannedResponse>("unary", this._transport, method, opt, input);
    }
}
