// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IdentityService } from "./identity_service";
import type { ListBansResponse } from "./identity_service";
import type { IsBannedResponse } from "./identity_service";
import type { SetBanStatusResponse } from "./identity_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { IsModeratorResponse } from "./identity_service";
import type { SignedMessage } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Identity APIs. Every method takes a SignedMessage wrapping a
 * serialized ModerationRequest (and, in `body`, the serialized
 * endpoint-specific request), signed by one of `moderator_identity`'s
 * authorized keys.
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export interface IIdentityServiceClient {
    /**
     * Returns whether `moderator_identity` is a moderator on this server.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsModeratorResponse>;
    /**
     * Bans or unbans an identity on this server. Requires the signer to be
     * a moderator.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, SetBanStatusResponse>;
    /**
     * Returns whether an identity is banned on this server. Requires the
     * signer to be a moderator.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsBannedResponse>;
    /**
     * Lists the identities banned on this server. Requires the signer to
     * be a moderator.
     *
     * @generated from protobuf rpc: ListBans
     */
    listBans(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, ListBansResponse>;
}
/**
 * *
 * Identity APIs. Every method takes a SignedMessage wrapping a
 * serialized ModerationRequest (and, in `body`, the serialized
 * endpoint-specific request), signed by one of `moderator_identity`'s
 * authorized keys.
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export class IdentityServiceClient implements IIdentityServiceClient, ServiceInfo {
    typeName = IdentityService.typeName;
    methods = IdentityService.methods;
    options = IdentityService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns whether `moderator_identity` is a moderator on this server.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsModeratorResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, IsModeratorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Bans or unbans an identity on this server. Requires the signer to be
     * a moderator.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, SetBanStatusResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, SetBanStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Returns whether an identity is banned on this server. Requires the
     * signer to be a moderator.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, IsBannedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, IsBannedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Lists the identities banned on this server. Requires the signer to
     * be a moderator.
     *
     * @generated from protobuf rpc: ListBans
     */
    listBans(input: SignedMessage, options?: RpcOptions): UnaryCall<SignedMessage, ListBansResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignedMessage, ListBansResponse>("unary", this._transport, method, opt, input);
    }
}
