// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * PublicKeys signs all events on the polycentric network. There is usually one public key per account, per device.
 *
 * @generated from protobuf message polycentric.v2.PublicKey
 */
export interface PublicKey {
    /**
     * Type of key used. Defaults to ED25519.
     *
     * @generated from protobuf field: polycentric.v2.KeyType key_type = 1
     */
    keyType: KeyType;
    /**
     * Value of the key
     *
     * @generated from protobuf field: bytes key = 2
     */
    key: Uint8Array;
}
/**
 * ID is the (ed25519) signature
 *
 * @generated from protobuf message polycentric.v2.IdentityId
 */
export interface IdentityId {
    /**
     * ed25519 signature from initial device
     *
     * @generated from protobuf field: bytes value = 1
     */
    value: Uint8Array;
}
/**
 * Identity
 *
 * @generated from protobuf message polycentric.v2.Identity
 */
export interface Identity {
    /**
     * Unique ID of the Identity
     *
     * @generated from protobuf field: polycentric.v2.IdentityId id = 1
     */
    id?: IdentityId;
    /**
     * Initial public key that forged the identity
     *
     * @generated from protobuf field: polycentric.v2.PublicKey initial_public_key = 2
     */
    initialPublicKey?: PublicKey;
}
/**
 * Identities are issued by other Public Keys that have the necessary permissions
 *
 * @generated from protobuf message polycentric.v2.IdentityIssue
 */
export interface IdentityIssue {
    /**
     * Device that the identity will be issued to
     *
     * @generated from protobuf field: polycentric.v2.PublicKey public_key = 1
     */
    publicKey?: PublicKey;
    /**
     * Permissions that the identity will have
     *
     * @generated from protobuf field: repeated polycentric.v2.IdentityPermission permissions = 2
     */
    permissions: IdentityPermission[];
}
/**
 * Identities can be revoked by other Public Keys that have the necessary permissions
 *
 * @generated from protobuf message polycentric.v2.IdentityRevoke
 */
export interface IdentityRevoke {
    /**
     * PublicKey to be revoked
     *
     * @generated from protobuf field: polycentric.v2.PublicKey public_key = 1
     */
    publicKey?: PublicKey;
}
/**
 * Published by a key that has been issued permissions via IdentityIssue.
 * Completes the two-sided handshake: IdentityIssue (by issuer) + IdentityClaim (by recipient).
 * The CRDT replay considers a key fully authorized only when both events exist.
 *
 * @generated from protobuf message polycentric.v2.IdentityClaim
 */
export interface IdentityClaim {
    /**
     * The identity being claimed (matches the IdentityId from the Identity event)
     *
     * @generated from protobuf field: polycentric.v2.IdentityId identity = 1
     */
    identity?: IdentityId;
}
/**
 * @generated from protobuf enum polycentric.v2.KeyType
 */
export enum KeyType {
    /**
     * @generated from protobuf enum value: KEY_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: KEY_TYPE_ED25519 = 1;
     */
    ED25519 = 1
}
/**
 * Permissions that can be assigned to a PublicKey
 *
 * @generated from protobuf enum polycentric.v2.IdentityPermission
 */
export enum IdentityPermission {
    /**
     * @generated from protobuf enum value: IDENTITY_PERMISSION_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * PublicKey will have full control over the identity
     *
     * @generated from protobuf enum value: IDENTITY_PERMISSION_ALL = 1;
     */
    ALL = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class PublicKey$Type extends MessageType<PublicKey> {
    constructor() {
        super("polycentric.v2.PublicKey", [
            { no: 1, name: "key_type", kind: "enum", T: () => ["polycentric.v2.KeyType", KeyType, "KEY_TYPE_"] },
            { no: 2, name: "key", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<PublicKey>): PublicKey {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.keyType = 0;
        message.key = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<PublicKey>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PublicKey): PublicKey {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.KeyType key_type */ 1:
                    message.keyType = reader.int32();
                    break;
                case /* bytes key */ 2:
                    message.key = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PublicKey, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.KeyType key_type = 1; */
        if (message.keyType !== 0)
            writer.tag(1, WireType.Varint).int32(message.keyType);
        /* bytes key = 2; */
        if (message.key.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.key);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PublicKey
 */
export const PublicKey = new PublicKey$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentityId$Type extends MessageType<IdentityId> {
    constructor() {
        super("polycentric.v2.IdentityId", [
            { no: 1, name: "value", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<IdentityId>): IdentityId {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.value = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<IdentityId>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityId): IdentityId {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes value */ 1:
                    message.value = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityId, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes value = 1; */
        if (message.value.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityId
 */
export const IdentityId = new IdentityId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Identity$Type extends MessageType<Identity> {
    constructor() {
        super("polycentric.v2.Identity", [
            { no: 1, name: "id", kind: "message", T: () => IdentityId },
            { no: 2, name: "initial_public_key", kind: "message", T: () => PublicKey }
        ]);
    }
    create(value?: PartialMessage<Identity>): Identity {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Identity>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Identity): Identity {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.IdentityId id */ 1:
                    message.id = IdentityId.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* polycentric.v2.PublicKey initial_public_key */ 2:
                    message.initialPublicKey = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.initialPublicKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Identity, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.IdentityId id = 1; */
        if (message.id)
            IdentityId.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.PublicKey initial_public_key = 2; */
        if (message.initialPublicKey)
            PublicKey.internalBinaryWrite(message.initialPublicKey, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Identity
 */
export const Identity = new Identity$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentityIssue$Type extends MessageType<IdentityIssue> {
    constructor() {
        super("polycentric.v2.IdentityIssue", [
            { no: 1, name: "public_key", kind: "message", T: () => PublicKey },
            { no: 2, name: "permissions", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["polycentric.v2.IdentityPermission", IdentityPermission, "IDENTITY_PERMISSION_"] }
        ]);
    }
    create(value?: PartialMessage<IdentityIssue>): IdentityIssue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.permissions = [];
        if (value !== undefined)
            reflectionMergePartial<IdentityIssue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityIssue): IdentityIssue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PublicKey public_key */ 1:
                    message.publicKey = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.publicKey);
                    break;
                case /* repeated polycentric.v2.IdentityPermission permissions */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.permissions.push(reader.int32());
                    else
                        message.permissions.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityIssue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PublicKey public_key = 1; */
        if (message.publicKey)
            PublicKey.internalBinaryWrite(message.publicKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.IdentityPermission permissions = 2; */
        if (message.permissions.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.permissions.length; i++)
                writer.int32(message.permissions[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityIssue
 */
export const IdentityIssue = new IdentityIssue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentityRevoke$Type extends MessageType<IdentityRevoke> {
    constructor() {
        super("polycentric.v2.IdentityRevoke", [
            { no: 1, name: "public_key", kind: "message", T: () => PublicKey }
        ]);
    }
    create(value?: PartialMessage<IdentityRevoke>): IdentityRevoke {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<IdentityRevoke>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityRevoke): IdentityRevoke {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PublicKey public_key */ 1:
                    message.publicKey = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.publicKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityRevoke, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PublicKey public_key = 1; */
        if (message.publicKey)
            PublicKey.internalBinaryWrite(message.publicKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityRevoke
 */
export const IdentityRevoke = new IdentityRevoke$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentityClaim$Type extends MessageType<IdentityClaim> {
    constructor() {
        super("polycentric.v2.IdentityClaim", [
            { no: 1, name: "identity", kind: "message", T: () => IdentityId }
        ]);
    }
    create(value?: PartialMessage<IdentityClaim>): IdentityClaim {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<IdentityClaim>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityClaim): IdentityClaim {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.IdentityId identity */ 1:
                    message.identity = IdentityId.internalBinaryRead(reader, reader.uint32(), options, message.identity);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityClaim, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.IdentityId identity = 1; */
        if (message.identity)
            IdentityId.internalBinaryWrite(message.identity, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityClaim
 */
export const IdentityClaim = new IdentityClaim$Type();
