// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/messages.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PublicKey } from "./keypair";
/**
 * @generated from protobuf message polycentric.v2.SignedMessage
 */
export interface SignedMessage {
    /**
     * @generated from protobuf field: polycentric.v2.PublicKey signed_by = 1
     */
    signedBy?: PublicKey;
    /**
     * @generated from protobuf field: bytes signature = 2
     */
    signature: Uint8Array;
    /**
     * @generated from protobuf field: bytes message_bytes = 3
     */
    messageBytes: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class SignedMessage$Type extends MessageType<SignedMessage> {
    constructor() {
        super("polycentric.v2.SignedMessage", [
            { no: 1, name: "signed_by", kind: "message", T: () => PublicKey },
            { no: 2, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "message_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SignedMessage>): SignedMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signature = new Uint8Array(0);
        message.messageBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SignedMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SignedMessage): SignedMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PublicKey signed_by */ 1:
                    message.signedBy = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.signedBy);
                    break;
                case /* bytes signature */ 2:
                    message.signature = reader.bytes();
                    break;
                case /* bytes message_bytes */ 3:
                    message.messageBytes = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SignedMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PublicKey signed_by = 1; */
        if (message.signedBy)
            PublicKey.internalBinaryWrite(message.signedBy, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bytes signature = 2; */
        if (message.signature.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.signature);
        /* bytes message_bytes = 3; */
        if (message.messageBytes.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.messageBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SignedMessage
 */
export const SignedMessage = new SignedMessage$Type();
