_default:
    @just --list

# Install deps, build core + react, then run web dev server
run-web:
    npm install && cd packages/polycentric-core && npm run generate && npm run build && cd ../polycentric-react && npm run build && cd ../polycentric-web && npm run dev

# Test legacy core
test-core:
    cd packages/polycentric-core && npm test
