syntax = "proto3";
package polycentric.v2;

import "polycentric/v2/common.proto";
import "polycentric/v2/events.proto";
import "polycentric/v2/server.proto";

enum NotificationType {
  NOTIFICATION_TYPE_TYPE_UNSPECIFIED = 0;
  NOTIFICATION_TYPE_FOLLOW = 1;
  NOTIFICATION_TYPE_REPLY = 2;
  NOTIFICATION_TYPE_REPOST = 3;
  NOTIFICATION_TYPE_REACTION = 4;
}

message Notification {
  // Event that triggered the notification
  EventBundle trigger_event = 1;
  // Event that the notification is in relation to
  EventBundle target_event = 2;
  // Type of the notification
  NotificationType type = 3;
}

message ListNotificationsRequest {
  string identity = 1;
  // Return the 1 X number of notifications
  optional uint32 first = 2;
  // Return notifications after a cursor
  optional string after = 3;
}

message ListNotificationsResponse {
  repeated Notification notifications = 1;
  // Events that help the client resolve with fewer network calls
  repeated EventHint event_hints = 2;
  PageInfo page_info = 3;
}

message RegisterPushNotificationRequest {
  string service = 1;
  string token = 2;
}

message RegisterPushNotificationResponse {}

message UnregisterPushNotificationRequest {
  string service = 1;
  string token = 2;
}

message UnregisterPushNotificationResponse {}

/**
 * Push notifications provided by polycentric servers
 */
service NotificationService {
  // Returns notifications for a user
  rpc ListNotifications(ListNotificationsRequest) returns (ListNotificationsResponse);
  // This endpoint expects a signed RegisterPushNotificationRequest message
  rpc RegisterPushNotifications(SignedMessage) returns (RegisterPushNotificationResponse);

  // This endpoint expects a signed UnregisterPushNotificationRequest message
  rpc UnregisterPushNotifications(SignedMessage) returns (UnregisterPushNotificationResponse);
}
